### ISSUE TITLE
Is there a way to set drawable as the FloatingActionsMenu icon?

### ISSUE THREAD

**Issue by egedib** [MSF-Jarvis/floating-action-button#1]
Hi!
I was wondering if I can change the plus sign when I'm using the Floating Actions Menu.
Is it possible somehow? I couldn't find an example.

**Comment by msfjarvis** [comment]
Not at the moment but I think I can make it happen.

**Comment by egedib** [comment]
Thanks!
Btw. that was fast! 😄

**Comment by msfjarvis** [comment]
I can't test this right now since I never updated the sample and it's currently unusable. Can you update to either [this](https://jitpack.io/#msfjarvis/floating-action-button/dev-SNAPSHOT) version or manually download the `aar` from [here](https://github.com/msfjarvis/floating-action-button/packages/59468) and test it for me?

Use the `fab_drawable` attribute on `FloatingActionsMenu` to set a custom drawable.

**Comment by egedib** [comment]
It's working!
Although the icon rotates when I open the menu, so it's a bit strange-looking, but it's good for me for now, thanks! 👍

**Comment by msfjarvis** [comment]
> It's working!
> Although the icon rotates when I open the menu, so it's a bit strange-looking, but it's good for me for now, thanks!

Good to know. I'll add another attribute to disable rotation tomorrow.

**Comment by msfjarvis** [comment]
> Although the icon rotates when I open the menu, so it's a bit strange-looking, but it's good for me for now, thanks!

Try [this](https://jitpack.io/#msfjarvis/floating-action-button/042ac7ebdd) with `app:fab_disableRotationOnExpand=true` on the `FloatingActionsMenu` view

**Comment by egedib** [comment]
It's working! Thank you!

**Comment by egedib** [comment]
Hm, I take my last message back - it is working, but if I use the current version, my buttons (everywhere on my app) change colors. Keep in mind I'm not an Android expert - my buttons were displayed using the accent color. Now the buttons have the primary color as their backgrounds.

Using the 3.1.0 solves the problem, but then I can't use the new features.
I tried to use dev-SNAPSHOT, but the problem still occurs.

**Comment by msfjarvis** [comment]
That's probably a regression from using Material 1.2 alpha in the library. I'll downgrade to 1.1.0 in `dev` after my exams today.

**Comment by msfjarvis** [comment]
@egedib I've switched `dev` back to MDC 1.0.0, can you test the JitPack snapshot and see if it's fixed for you?

**Comment by egedib** [comment]
Working beautifully, all of my problems are solved, thank you!

**Comment by msfjarvis** [comment]
Great, I'll tag a new version shortly.

**Comment by msfjarvis** [comment]
Version [3.2.0](https://github.com/msfjarvis/floating-action-button/releases/tag/3.2.0) is currently building on JitPack and will be up in a few minutes.
