### ISSUE TITLE
Fail in resolve Sync

### ISSUE THREAD

**Issue by joaoeudes7** [MSF-Jarvis/floating-action-button#4]
```
ERROR: Failed to resolve: com.github.msfjarvis:floating-action-button:3.1.0
Show in Project Structure dialog
Affected Modules: app
```

**Comment by msfjarvis** [comment]
Did you add the Jitpack repository to your app module?

**Comment by joaoeudes7** [comment]
Yes

**Comment by msfjarvis** [comment]
> Yes

The release [exists](https://jitpack.io/#msfjarvis/floating-action-button/3.1.0) on JitPack and resolves for my other projects so I can't think of any reason but misconfiguration on your end. Can you provide me your `build.gradle` and `app/build.gradle` files for review?

**Comment by joaoeudes7** [comment]
Sorry, the `{ url "https://jitpack.io" }` was not in the `allprojects`section.
Thanks by the support! :)
